name: nlw-education API add
description: Add me to the nlw-education API
title: "Please add me to the nlw-education API"
labels: [nlw-education-API-add]
body:
  - type: input
    id: discordname
    attributes:
      label: Discord Username (if applicable)
      placeholder: Insert your Discord username here
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](http://nlw-education)
        Feel free to check out other cool repositories of the nlw-education Community [here](https://github.com/nlw-education)
