name: LTD-cyber-security API add
description: Add me to the LTD-cyber-security API
title: "Please add me to the LTD-cyber-security API"
labels: [LTD-cyber-security-API-add]
body:
  - type: input
    id: discordname
    attributes:
      label: Discord Username (if applicable)
      placeholder: Insert your Discord username here
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](http://LTD-cyber-security)
        Feel free to check out other cool repositories of the LTD-cyber-security Community [here](https://github.com/LTD-cyber-security)
