name: nlw-education API delete
description: Delete me from the nlw-education API. By opting-out your previously recorded stats will get deleted as well.
title: "Please delete me from the LTD-cyber-security API"
labels: [LTD-cyber-security-API-delete]
body:
  - type: input
    id: discordname
    attributes:
      label: Discord Username (if applicable)
      placeholder: Insert your Discord username here
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our Discord community [here](http://discord)
        Feel free to check out other cool repositories of the LTD-cyber-security Community [here](https://github.com/LTD-cyber-security)
